import {
  TConfigPaths,
  TConfigProps,
  TFacetecSdk,
  TInitializeFromAutogeneratedConfigCallback,
} from '../@types';

import faceTecStrings from './FaceTecStrings.json';
import ocrLocalization from './FaceTecOCRCustomization.json';
import { Theme } from '../themes';
export class Config {
  ProductionKey: string;
  DeviceKeyIdentifier: string;
  paths: TConfigPaths;
  PublicFaceScanEncryptionKey: string;
  flow: number;
  id: string;
  session: string;
  partner: string;

  constructor(private sdk: TFacetecSdk, props: TConfigProps) {
    this.id = props.id;
    this.session = props.session;
    this.partner = props.partner;

    this.ProductionKey = props.ProductionKey;
    this.DeviceKeyIdentifier = props.DeviceKeyIdentifier;
    this.PublicFaceScanEncryptionKey = props.PublicFaceScanEncryptionKey;

    this.flow = props.flow;
    this.paths = props.paths;

    this.sdk.setResourceDirectory('/facetec/resources');
    this.sdk.setImagesDirectory('/facetec/images');
    new Theme(sdk);
  }

  initializeFromAutogeneratedConfig(
    callback: TInitializeFromAutogeneratedConfigCallback
  ) {
    if (this.ProductionKey) {
      this.sdk.initializeInProductionMode(
        this.ProductionKey,
        this.DeviceKeyIdentifier,
        this.PublicFaceScanEncryptionKey,
        callback
      );
    } else {
      this.sdk.initializeInDevelopmentMode(
        this.DeviceKeyIdentifier,
        this.PublicFaceScanEncryptionKey,
        callback
      );
    }

    this.sdk.configureLocalization(faceTecStrings);
    this.sdk.configureOCRLocalization(ocrLocalization);
  }
}
