import { TJSON } from '@interface/common';
import {
  TconfigProps,
  TFacetecSdk,
  TinitializeFromAutogeneratedConfigCallback,
} from './@types';

export class Config {
  DeviceKeyIdentifier: string;
  BaseURL: string;
  PublicFaceScanEncryptionKey: string;
  currentLowLightCustomization: TJSON;
  currentDynamicDimmingCustomization: TJSON;

  constructor(props: TconfigProps) {
    this.DeviceKeyIdentifier = props.DeviceKeyIdentifier;
    this.BaseURL = props.BaseURL;
    this.PublicFaceScanEncryptionKey = props.PublicFaceScanEncryptionKey;
  }

  initializeFromAutogeneratedConfig(
    sdk: TFacetecSdk,
    callback: TinitializeFromAutogeneratedConfigCallback
  ) {
    sdk.initializeInDevelopmentMode(
      this.DeviceKeyIdentifier,
      this.PublicFaceScanEncryptionKey,
      callback
    );
  }

  retrieveConfigurationWizardCustomization(sdk: TFacetecSdk) {
    const sdkImageDirectory = '/facetec/images/';

    // For Color Customization
    const outerBackgroundColor = '#ffffff';
    const frameColor = '#ffffff';
    const borderColor = '#417FB2';
    const ovalColor = '#417FB2';
    const dualSpinnerColor = '#417FB2';
    const textColor = '#417FB2';
    const buttonAndFeedbackBarColor = '#417FB2';
    const buttonAndFeedbackBarTextColor = '#ffffff';
    const buttonColorHighlight = '#396E99';
    const buttonColorDisabled = '#B9CCDE';

    // For Frame Corner Radius Customization
    let frameCornerRadius = '20px';

    // For Cancel Button Customization
    const cancelButtonImage = sdkImageDirectory + 'FaceTec_cancel.png';
    const cancelButtonLocation = sdk.FaceTecCancelButtonLocation.TopLeft;

    // For image Customization
    const yourAppLogoImage = sdkImageDirectory + 'logo.svg';
    const securityWatermarkImage =
      sdk.FaceTecSecurityWatermarkImage.FaceTec_ZoOm;

    // Set a default customization
    const defaultCustomization = new sdk.FaceTecCustomization();

    // Set Frame Customization
    defaultCustomization.frameCustomization.borderCornerRadius =
      frameCornerRadius;
    defaultCustomization.frameCustomization.backgroundColor = frameColor;
    defaultCustomization.frameCustomization.borderColor = borderColor;

    // Set Overlay Customization
    defaultCustomization.overlayCustomization.brandingImage = yourAppLogoImage;
    defaultCustomization.overlayCustomization.backgroundColor =
      outerBackgroundColor;

    // Set Guidance Customization
    defaultCustomization.guidanceCustomization.backgroundColors = frameColor;
    defaultCustomization.guidanceCustomization.foregroundColor = textColor;
    defaultCustomization.guidanceCustomization.buttonBackgroundNormalColor =
      buttonAndFeedbackBarColor;
    defaultCustomization.guidanceCustomization.buttonBackgroundDisabledColor =
      buttonColorDisabled;
    defaultCustomization.guidanceCustomization.buttonBackgroundHighlightColor =
      buttonColorHighlight;
    defaultCustomization.guidanceCustomization.buttonTextNormalColor =
      buttonAndFeedbackBarTextColor;
    defaultCustomization.guidanceCustomization.buttonTextDisabledColor =
      buttonAndFeedbackBarTextColor;
    defaultCustomization.guidanceCustomization.buttonTextHighlightColor =
      buttonAndFeedbackBarTextColor;
    defaultCustomization.guidanceCustomization.retryScreenImageBorderColor =
      borderColor;
    defaultCustomization.guidanceCustomization.retryScreenOvalStrokeColor =
      borderColor;

    // Set Oval Customization
    defaultCustomization.ovalCustomization.strokeColor = ovalColor;
    defaultCustomization.ovalCustomization.progressColor1 = dualSpinnerColor;
    defaultCustomization.ovalCustomization.progressColor2 = dualSpinnerColor;

    // Set Feedback Customization
    defaultCustomization.feedbackCustomization.backgroundColor =
      buttonAndFeedbackBarColor;
    defaultCustomization.feedbackCustomization.textColor =
      buttonAndFeedbackBarTextColor;

    // Set Cancel Customization
    defaultCustomization.cancelButtonCustomization.customImage =
      cancelButtonImage;
    defaultCustomization.cancelButtonCustomization.location =
      cancelButtonLocation;

    // Set Security Watermark Customization
    defaultCustomization.securityWatermarkCustomization.setSecurityWatermarkImage(
      securityWatermarkImage
    );

    // Set Result Screen Customization
    defaultCustomization.resultScreenCustomization.backgroundColors =
      frameColor;
    defaultCustomization.resultScreenCustomization.foregroundColor = textColor;
    defaultCustomization.resultScreenCustomization.activityIndicatorColor =
      buttonAndFeedbackBarColor;
    defaultCustomization.resultScreenCustomization.resultAnimationBackgroundColor =
      buttonAndFeedbackBarColor;
    defaultCustomization.resultScreenCustomization.resultAnimationForegroundColor =
      buttonAndFeedbackBarTextColor;
    defaultCustomization.resultScreenCustomization.uploadProgressFillColor =
      buttonAndFeedbackBarColor;

    // Set ID Scan Customization
    defaultCustomization.idScanCustomization.selectionScreenBackgroundColors =
      frameColor;
    defaultCustomization.idScanCustomization.selectionScreenForegroundColor =
      textColor;
    defaultCustomization.idScanCustomization.reviewScreenBackgroundColors =
      frameColor;
    defaultCustomization.idScanCustomization.reviewScreenForegroundColor =
      buttonAndFeedbackBarTextColor;
    defaultCustomization.idScanCustomization.reviewScreenTextBackgroundColor =
      buttonAndFeedbackBarColor;
    defaultCustomization.idScanCustomization.captureScreenForegroundColor =
      buttonAndFeedbackBarTextColor;
    defaultCustomization.idScanCustomization.captureScreenTextBackgroundColor =
      buttonAndFeedbackBarColor;
    defaultCustomization.idScanCustomization.buttonBackgroundNormalColor =
      buttonAndFeedbackBarColor;
    defaultCustomization.idScanCustomization.buttonBackgroundDisabledColor =
      buttonColorDisabled;
    defaultCustomization.idScanCustomization.buttonBackgroundHighlightColor =
      buttonColorHighlight;
    defaultCustomization.idScanCustomization.buttonTextNormalColor =
      buttonAndFeedbackBarTextColor;
    defaultCustomization.idScanCustomization.buttonTextDisabledColor =
      buttonAndFeedbackBarTextColor;
    defaultCustomization.idScanCustomization.buttonTextHighlightColor =
      buttonAndFeedbackBarTextColor;
    defaultCustomization.idScanCustomization.captureScreenBackgroundColor =
      frameColor;
    defaultCustomization.idScanCustomization.captureFrameStrokeColor =
      borderColor;

    // Set Initial Loading Customization
    defaultCustomization.initialLoadingAnimationCustomization.backgroundColor =
      buttonAndFeedbackBarTextColor;
    defaultCustomization.initialLoadingAnimationCustomization.foregroundColor =
      buttonAndFeedbackBarColor;

    return defaultCustomization;
  }

  retrieveLowLightConfigurationWizardCustomization(sdk: TFacetecSdk) {
    const defaultCustomization =
      this.retrieveConfigurationWizardCustomization(sdk);
    this.currentLowLightCustomization = defaultCustomization;

    return defaultCustomization;
  }

  retrieveDynamicDimmingConfigurationWizardCustomization(sdk: TFacetecSdk) {
    const defaultCustomization =
      this.retrieveConfigurationWizardCustomization(sdk);
    this.currentDynamicDimmingCustomization = defaultCustomization;

    return defaultCustomization;
  }
}
