export type TconfigProps = Record<
  'DeviceKeyIdentifier' | 'BaseURL' | 'PublicFaceScanEncryptionKey',
  string
>;

export type TinitializeFromAutogeneratedConfigCallback = (
  result: boolean
) => void;
