export type configPropsType = Record<
  'DeviceKeyIdentifier' | 'BaseURL' | 'PublicFaceScanEncryptionKey',
  string
>;

export type initializeFromAutogeneratedConfigCallbackType = (
  result: boolean
) => void;
