import { Config } from '../Config';
import { generateUUId } from './../utilities';
import { EnrollmentProcessor, PhotoIDMatchProcessor } from '../processors';
import { facetecSdkType } from '../@types';
import {
  latestNetworkResponseStatusType,
  latestProcessorType,
  sessionTokenCallbackType,
} from './@types';
import {
  FaceTecIDScanResult,
  FaceTecSessionResult,
} from '../declarations/FaceTecPublicApi';

export class Controller {
  latestEnrollmentIdentifier = '';
  latestSessionResult = null;
  latestIDScanResult = null;
  latestProcessor: latestProcessorType;

  constructor(private sdk: facetecSdkType, private cfg: Config) {
    this.sdk.setResourceDirectory('/facetec/resources');
    this.sdk.setImagesDirectory('/facetec/images');
    this.cfg.initializeFromAutogeneratedConfig(
      this.sdk,
      (initializedSuccessfully) => {
        if (initializedSuccessfully) {
          console.log('initializedSuccessfully');

          // AppUtilities.enableControlButtons();
          // AppUtilities.setVocalGuidanceSoundFiles();
          // AppUtilities.setOCRLocalization();
          /* AdditionalScreens.setServerUpgradeStyling(
            document.getElementById('controls'),
            exitAdditionalScreen
          ); */
        }

        /* AppUtilities.displayStatus(
          sdk.getFriendlyDescriptionForFaceTecSDKStatus(
            sdk.getStatus()
          )
        ); */
      }
    );
  }

  onEnrollUserPressed() {
    // AppUtilities.fadeOutMainUIAndPrepareForSession();

    this.getSessionToken((sessionToken: string) => {
      this.latestEnrollmentIdentifier = `browser_app_${generateUUId()}`;
      this.latestProcessor = new EnrollmentProcessor(
        sessionToken,
        this.sdk,
        this.cfg,
        this
      );
    });
  }

  onPhotoIDMatchPressed() {
    // AppUtilities.fadeOutMainUIAndPrepareForSession();

    this.getSessionToken((sessionToken: string) => {
      this.latestEnrollmentIdentifier = `browser_app_${generateUUId()}`;
      this.latestProcessor = new PhotoIDMatchProcessor(
        sessionToken,
        this.sdk,
        this.cfg,
        this
      );
    });
  }

  onVocalGuidanceSettingsButtonPressed() {
    console.log('onVocalGuidanceSettingsButtonPressed');

    // AppUtilities.setVocalGuidanceMode();
  }

  onViewAuditTrailPressed() {
    console.log('onViewAuditTrailPressed');
    // console.log(this.latestSessionResult, this.latestIDScanResult);

    // AppUtilities.showAuditTrailImages(latestSessionResult, latestIDScanResult);
  }

  onComplete(
    sessionResult: FaceTecSessionResult,
    idScanResult: FaceTecIDScanResult,
    latestNetworkResponseStatus: latestNetworkResponseStatusType
  ) {
    this.latestSessionResult = sessionResult;
    this.latestIDScanResult = idScanResult;

    // console.log(this.latestSessionResult);
    // console.log(this.latestIDScanResult);
    // showAdditionalScreensServerIsDown();

    if (this.latestProcessor.isSuccess()) {
      // AppUtilities.displayStatus('Success');
    } else {
      if (
        this.isNetworkResponseServerIsOffline(latestNetworkResponseStatus) ===
        true
      ) {
        // this.showAdditionalScreensServerIsDown();

        return;
      }
    }

    // AppUtilities.showMainUI();
  }

  isNetworkResponseServerIsOffline(networkResponseStatus: number) {
    return networkResponseStatus >= 500;
  }

  getSessionToken(sessionTokenCallback: sessionTokenCallbackType) {
    const controller = this;
    const XHR = new XMLHttpRequest();
    let sessionTokenErrorHasBeenHandled = false;

    XHR.open('GET', this.cfg.BaseURL + '/session-token');
    XHR.setRequestHeader('X-Device-Key', this.cfg.DeviceKeyIdentifier);
    XHR.setRequestHeader(
      'X-User-Agent',
      this.sdk.createFaceTecAPIUserAgentString('')
    );

    XHR.onreadystatechange = function () {
      if (this.readyState === XMLHttpRequest.DONE) {
        var sessionToken = '';
        try {
          sessionToken = JSON.parse(this.responseText).sessionToken;
          if (typeof sessionToken !== 'string') {
            if (sessionTokenErrorHasBeenHandled === false) {
              sessionTokenErrorHasBeenHandled = true;
              if (controller.isNetworkResponseServerIsOffline(XHR.status)) {
                controller.showAdditionalScreensServerIsDown();
              } else {
                controller.onServerSessionTokenError();
              }
            }

            return;
          }
        } catch (_a) {
          if (sessionTokenErrorHasBeenHandled === false) {
            sessionTokenErrorHasBeenHandled = true;
            if (controller.isNetworkResponseServerIsOffline(XHR.status)) {
              controller.showAdditionalScreensServerIsDown();
            } else {
              controller.onServerSessionTokenError();
            }
          }

          return;
        }
        // AppUtilities.hideLoadingSessionToken();
        sessionTokenCallback(sessionToken);
      }
    };

    XHR.onerror = function () {
      if (sessionTokenErrorHasBeenHandled === false) {
        sessionTokenErrorHasBeenHandled = true;
        if (controller.isNetworkResponseServerIsOffline(XHR.status)) {
          controller.showAdditionalScreensServerIsDown();
        } else {
          controller.onServerSessionTokenError();
        }
      }
    };

    XHR.send();

    window.setTimeout(function () {
      if (XHR.readyState !== XMLHttpRequest.DONE) {
        // AppUtilities.showLoadingSessionToken();
      }
    }, 3000);
  }

  onServerSessionTokenError() {
    console.log('onServerSessionTokenError');

    // AppUtilities.handleErrorGettingServerSessionToken();
  }

  showAdditionalScreensServerIsDown() {
    console.log('showAdditionalScreensServerIsDown');

    // AdditionalScreens.showServerUpGradeView();
  }

  clearLatestEnrollmentIdentifier() {
    this.latestEnrollmentIdentifier = '';
  }

  getLatestEnrollmentIdentifier() {
    return this.latestEnrollmentIdentifier;
  }
}
