import { facetecSdkType } from '../@types';
import { Config } from './Config';

export class Controller {
  constructor(sdk: facetecSdkType, cfg: Config) {
    // console.log(sdk);

    sdk.setResourceDirectory('/facetec/resources');
    sdk.setImagesDirectory('/facetec/images');
    cfg.initializeFromAutogeneratedConfig(sdk, (initializedSuccessfully) => {
      if (initializedSuccessfully) {
        console.log(initializedSuccessfully);

        // AppUtilities.enableControlButtons();
        // AppUtilities.setVocalGuidanceSoundFiles();
        // AppUtilities.setOCRLocalization();
        /* AdditionalScreens.setServerUpgradeStyling(
            document.getElementById('controls'),
            exitAdditionalScreen
          ); */
      }

      /* AppUtilities.displayStatus(
          FaceTecSDK.getFriendlyDescriptionForFaceTecSDKStatus(
            FaceTecSDK.getStatus()
          )
        ); */
    });
  }

  onEnrollUserPressed() {
    console.log('onEnrollUserPressed');

    // AppUtilities.fadeOutMainUIAndPrepareForSession();

    /* getSessionToken(function (sessionToken) {
      latestEnrollmentIdentifier =
        'browser_sample_app_' + AppUtilities.generateUUId();
        latestProcessor = new EnrollmentProcessor(sessionToken, App);
      }); */
  }

  onPhotoIDMatchPressed() {
    console.log('onPhotoIDMatchPressed');
    // AppUtilities.fadeOutMainUIAndPrepareForSession();

    /* getSessionToken(function (sessionToken) {
      latestEnrollmentIdentifier =
        'browser_sample_app_' + AppUtilities.generateUUId();
      latestProcessor = new PhotoIDMatchProcessor(sessionToken, App);
    }); */
  }

  onVocalGuidanceSettingsButtonPressed() {
    console.log('onVocalGuidanceSettingsButtonPressed');

    // AppUtilities.setVocalGuidanceMode();
  }

  onViewAuditTrailPressed() {
    console.log('onViewAuditTrailPressed');

    // AppUtilities.showAuditTrailImages(latestSessionResult, latestIDScanResult);
  }
}
